name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *" # Run at 3am UTF+8 every day

jobs:
  sync:
    name: Sync with upstream docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Fetch upstream changes
        id: fetch-changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/pallets/flask.git
          git fetch upstream
          git merge upstream/2.0.x -m "Merge upstream changes into 'main' by GitHub Actions"
          # If docs/ has changes, continue below steps otherwise abort
          git diff --name-only origin/main HEAD | grep -q -e '^docs/'

      - name: Generate Translation
        run: |
          pip install -r requirements/docs.txt
          pip install PyGithub
          pip install -e .
          cd docs
          make gettext
          sphinx-intl update -p _build/gettext
          cd ..
          git add docs/
          git commit -m "Update po files by GitHub Actions"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue
        shell: python
        run: |
          import subprocess, os
          from github import Github
          g = Github(os.getenv('GITHUB_TOKEN'))
          changed = subprocess.check_output("git diff --name-only origin/main HEAD | grep -e '^docs/locales/'", shell=True, text=True)
          body = "## Changed po files\n\n" + "\n".join(f"- [ ] {line}" for line in changed.splitlines() if line.strip())
          repo = g.get_repo(os.getenv('REPO'))
          issue = repo.create_issue(title=os.getenv('ISSUE_TITLE'), body=body)
          print(issue)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE_TITLE: New updates of .po files
